from flask import Flask, render_template, request
#import requests
import subprocess
import os
import logging
from config.config import INFORMATION_PROCESSING_URL


app = Flask(__name__)


@app.route('/')
def index():
    logging.debug("REQUEST / --> RENDERING TEMPLATE")
    return render_template('home.html')

@app.route('/launch-haiq', methods=['POST'])
def launch_haiq():
    """
    Recieved the file generated by the the Haiq File Generator
    Save the file in the corresponding path
    Launch the program
    """
    recieved_file = None
    path_to_save = "/home .../QuantumClassicalApp/model.haiq" # To be completed
    logging.debug("HAIQ LAUNCHER --> /launch-haiq")
    if request.files:
        logging.debug("HAIQ LAUNCHER --> File recieved")
        # Revisar nombre de ['haiqFile']
        recieved_file = request.files['haiqFile']
        if recieved_file != None:
            print("ARCHIVO RECIBIDO Y LEIDO CORRECTAMENTE")
            logging.debug("HAIQ LAUNCHER --> File read correctly")
            if not os.path.exists(path_to_save):
                try:
                    os.makedirs(path_to_save)
                    #Create the run.sh 
                except Exception as e:
                    return f"Error al crear la carpeta: {e}", 500
            #Saving file
            recieved_file.save(path_to_save) #Tomar la ruta de donde los ejemplos
            #Lanzar run.sh
            script_path = os.path.join(path_to_save,'run.sh')

            try:
                result = subprocess.run(['bash', script_path], cwd=path_to_save, check=True, capture_output=True, text=True)
                output = result.stdout 
                #Añadir al script una salida (Tipo 200 si okey)
            except subprocess.CalledProcessError as e:
                print("SE HA PRODUCIDO UNA EXCEPCIÓN AL EJECUTAR EL SCRIPT")
                print(e)

            haiq_result_path = '' #To Complete
            haiq_result = None
            if os.path.exists(haiq_result_path):
                with open(haiq_result_path, 'r') as resultado_file:
                    haiq_result = resultado_file.read()
                if haiq_result != None:
                    print("HAIQ RESULT READED")
                    # Mandar resultado a INFO PROCESSING
                else:
                    print("ERROR AL LEER RESULTADO DE HAIQ")
            else:
                print("RESULTADO DE HAIQ NO ENCONTRADO")


        else:
            print("RECIBIDO PERO NO LEIDO CORRECTAMENTE")
            logging.debug("HAIQ LAUNCHER --> File didn't read correctly")

    else:
        logging.debug("HAIQ LAUNCHER --> Something was wrong :(")
        print("NO SE HA RECIBIDO ARCHIVO HAIQ")




if __name__ == '__main__':
    logging.basicConfig(filename=os.getcwd()+'/launcher.log', encoding='utf-8', level=logging.DEBUG, format='%(asctime)s %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p') #CREATING LOGGING CONFIGURATION
    #app.run(host="127.0.0.1", port=8585,debug=True)
    app.run(host="0.0.0.0", port=8888,debug=True)