TOPIC_WEB = 'update-web'
TOPIC_QPU = 'information-qpu'
TOPIC_QPU_CANDIDATES = 'qpu-candidates'
TOPIC_CPU = 'information-cpu'
TOPIC_CPU_CANDIDATES = 'cpu-candidates'
TOPIC_RESET_PHASES = 'reset-phases'
