openapi: 3.1.0
info:
  title: Binary search microservice
  description: |
    This is a description of a service that is in charge of recieving the corresponding information
     of the temperatures measured and tries to find any anomaly.
  # Extension for requirements
  x-req:
    $ref: ../REQ/binary_search.yml
  version: 1.0.0
servers:
- url:
- description: Classical machine in wich the server is going to be deployed
paths:
  /status:
      get:
        summary: Show the status of the microservice.
        description: Function that returns the availability of the microservice.
        responses:
          "200":
            description: "Online" 
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    result:
                      type: string
                      description: |
                        The microservice is online.
          default:
            description: error produced.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    result:
                      type: string
                      description: |
                        An error ocurred.
  /launchBinarySearch/{temperatures_values}:
    get:
      summary: Launch the binary search algorithim.
      description: Function that execute the binary search algorithm.
      responses:
        "200":
          description: "OK" 
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: |
                      Binary search algorithim launched.
        default:
          description: error produced.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: |
                      An error occured while launching the analysis.
    parameters:
    - name: temp
      in: paths
      description: Information about temperatures
      required: true
      schema:
        type: array
        items:
          type: string # Lo he puesto como string porque despues en el proceso de la petición se puede procesar.
      style: simple    
