openapi: 3.1.0
info:
  title: Grover microservice
  description: |
    This is a description of a service that is in charge of recieving the corresponding quantum information
     of the temperatures measured.
  # Extension for requirements
  x-req:
    $ref: ./requirements/requirements_grover.yml
  version: 1.0.0
servers:
- url:
- description: Classical machine in wich the server is going to be deployed
- url:
- description: Quantum machine in wich the algorithm is going to be executed.
paths:
  /status:
      get:
        summary: Show the status of the microservice.
        description: Function that returns the availability of the microservice.
        responses:
          "200":
            description: "Online" 
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    result:
                      type: string
                      description: |
                        The microservice is online.
          default:
            description: error produced.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    result:
                      type: string
                      description: |
                        An error ocurred.
  /launchGrover/{qubits_values}:
    get:
      summary: Launch the grover algorithim.
      description: Function that execute the quantum circuit of grover algorithm.
      responses:
        "200":
          description: "OK" 
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: |
                      Grover algorithim launched.
        default:
          description: error produced.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: |
                      An error occured while launching the analysis.
    parameters:
    - name: qubits
      in: paths
      description: Quantum information of temperatures
      required: true
      schema:
        type: array
        items:
          type: string # Lo he puesto como string porque despues en el proceso de la petición se puede procesar.
      style: simple    
