spil4ha: 1.0.0 #SPILab 4 hibrid architectures
context:
  type: object
  description: "Holds the main information of the requirements"
  id:
    type: string
    description: "Identifier of the microservice"
  api:
    type: uri
    description: "URI for the OpenAPI Specification of the microservice"
  mode:
    type: string
    description: "String to indicate the microservice mode of computing (CPU or QPU)"
  author:
    type: string
    description: "Optional field to indicate the creator of the file"
minimum-hw-req:
  type: object
  description: "Holds the minimum hardware requirements needed for a good performance of the microservice"
  cpu:
    type: integer
    format: int64
    description: "CPU cycles per second"
  ram:
    type: integer
    format: int64
    description: "Required memory needed for a correct execution"
  qubits:
    type: integer
    format: int64
    description: "Minimum number of qubits available in the quantum computer"
behaviour:
  type: object
  description: "Holds the values of behavioural requirements"
  requests:
    number_request:
      type: integer
      format: int64
      description: "Number of requests per minute"
    maximum_request_size:
      type: integer
      format: int64
      description: "Maximum size in bytes of a request"
  execution_time:
    type: integer
    format: int64
    description: "Maximun execution time of the classic microservice task"
  availability:
    type: integer
    format: int64
    description: "Number of online hours per day of the classic microservice"
  shots:
    type: integer
    format: int64
    description: "Number of shots of the quantum circuit"  